### ISSUE TITLE
Ship Invuln Bugs

### ISSUE THREAD

**Issue by Staethe** [Mijumaru3/GameDev1_Project2#19]
When objects respawn and hit the ship, the ship is still flashing but lives get decremented. Issue may be that invuln period is too long, and theres only a frame of vulnerability before being hit again sets it off.

Replicate by getting hit by multiple boxes in a row.

**Comment by Staethe** [comment]
Timing changed since boxes now are deleted & respawn on ship collision

**Comment by Mijumaru3** [comment]
Lowered time for invulnerability to 1 for time being (possibly to be tweaked later)
